services:
  elasticsearch:
    image: elasticsearch:8.17.3
    container_name: elasticsearch_local
    volumes:
      - './elasticdata:/usr/share/elasticsearch/data'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9292:9200
    deploy:
      resources:
        limits:
          memory: 8G
    restart: always
