services:
  elasticsearch:
    image: elasticsearch:8.17.3
    volumes:
      - './elasticdata:/usr/share/elasticsearch/data'
    user: "1000"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
