{
 "title": "Apache JMeter Grafana Dashboard | SpeckyFox Technologies",
 "description": "Monitor your Apache JMeter load test in real time with InfluxDB and Grafana. Get overall summary, error details and particular transaction response times. A dashboard by Speckyfox Technologies",
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   { "name": "Bucket", "query": "buckets()" },
   {
    "name": "Measurement",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurements(bucket:\"Grafana\")\r\n  |> keep(columns: [\"_value\"])\r\n  |> group()\r\n  |> distinct(column: \"_value\")\r\n  |> rename(columns: {_value: \"Measurement\"})\r\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Application statistics influxDB - JMeter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Number of Users",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"maxAT\")"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "gauge",
   "description": "This query is used to analyze and monitor the error rate as a percentage of total events in your performance testing data",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Measurement}\")\n  |> filter(fn: (r) => r[\"transaction\"] == \"all\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /count*/)\n  |> sum()\n  |> pivot(rowKey:[\"_measurement\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_value: float(v: r.countError) / float(v: r.count) * 100.0}))"
    }
   ]
  },
  {
   "title": "Errors By Status Codes",
   "type": "gauge",
   "description": "This query helps you analyze and monitor the distribution of response codes in your performance testing data. It provides insights into how often each response code occurs over time, which can be useful for identifying patterns and assessing the performance and reliability of your application under various scenarios",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> filter(fn: (r) => exists r[\"responseCode\"])\n  |> group(columns: [\"responseCode\"], mode:\"by\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> count()"
    }
   ]
  },
  {
   "title": "Individual transactions over time",
   "type": "timeseries",
   "description": "It calculates the rate of \"count\" events per second over a specified time range and for a specific application with the \"statut\" field set to \"all.\"",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  // |> filter(fn: (r) => r[\"transaction\"] != \"Latency API\" and r[\"transaction\"] != \"Latency\")\n  |> filter(fn: (r) => exists r.statut)\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")"
    }
   ]
  },
  {
   "title": "95 Percentiles Over Time (successful responses)",
   "type": "timeseries",
   "description": "This InfluxDB Flux query retrieves 95th percentile performance metrics for a specific application  when the \"statut\" is \"ok.\" It focuses on JMeter measurements within a specified time range and selects only metrics matching the pattern \"/pct95/.\"",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Measurement}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"ok\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /pct95/)"
    }
   ]
  },
  {
   "title": "Response Times Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Measurement}\")\n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avg\")\n  |> filter(fn: (r) => r[\"transaction\"] != \"Latency API\" and r[\"transaction\"] != \"Latency\")\n  |> group(columns: [\"transaction\"], mode: \"by\")"
    }
   ]
  },
  {
   "title": "Error Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Measurement}\")\n  |> filter(fn: (r) => r[\"responseMessage\"] != \"\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  }
 ]
}