services:
  elasticsearch:
    image: elasticsearch:9.0.1
    volumes:
      - '../elasticsearch/data:/usr/share/elasticsearch/data'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9278:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
