version: '3.5'
services:
  database:
    image: "postgres:15-alpine" # use latest official postgres version
    env_file:
      - postgresql.env # configure postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
